# Generated by Django 5.0.7 on 2024-07-11 12:35

import apps.application.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=17, validators=[apps.application.validators.validate_phone_number])),
                ('amount', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('spend_amount', models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Jismoniy Shaxs'), (1, 'Yuridik Shaxs')])),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Yangi'), (1, 'Moderatsiyada'), (2, 'Tasdiqlangan'), (3, 'Bekor Qilingan')], default=0)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(0, 'Naqd'), (1, 'Plastik Karta')])),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
